const FILE_STATUS = {
  IDLE: "IDLE",
  UPLOADING: "UPLOADING",
  UPLOADED: "UPLOADED",
  FAILED: "FAILED",
};

const UPLOAD_STATUS = {
  UPLOADING: "UPLOADING",
  PROCESSING: "PROCESSING",
  DONE: "DONE",
  FAILED: "FAILED",
};

const MAX_FILES = 5;
const MAX_SIZE = 100 * 1024 * 1024;
const DEFAULT_POLLING_INTERVAL = 5000;

export {
  FILE_STATUS,
  UPLOAD_STATUS,
  MAX_FILES,
  MAX_SIZE,
  DEFAULT_POLLING_INTERVAL,
};
